sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install: pip install tox-travis
script: tox
branches:
  only:
    - master
matrix:
  fast_finish: true
